### ISSUE TITLE
issues when you hit singup without entering anything.

### ISSUE THREAD

**Issue by snehaajency** [ajency/bottlebits#23]
1.highlight all groups for empty state.
2.if there is error and user gives input then the input should not appear in red 
3.on click of age group-lighten the group/highlight.
4.country inputs coming in red.
5.recaptcha when in empty state and hit ign up,should show an error message "this is a mandatory field"
6.recaptha and signup box gets red box around which is not correct

**Comment by HazelColaco19** [comment]
Rest are fixed. Following are remaining:

1.highlight all groups for empty state.
5.recaptcha when in empty state and hit ign up,should show an error message "this is a mandatory field"
6.recaptha and signup box gets red box around which is not correct

**Comment by snehaajency** [comment]
not fixed:
5.recaptcha when in empty state and hit ign up,should show an error message "this is a mandatory field"
6.recaptha and signup box gets red box around which is not correct
